CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS boards (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  name TEXT NOT NULL CHECK (char_length(trim(name)) > 0),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS tasks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  board_id BIGINT,
  title TEXT NOT NULL CHECK (char_length(trim(title)) > 0),
  description TEXT,
  status TEXT NOT NULL DEFAULT 'todo' CHECK (status IN ('backlog', 'todo', 'in_progress', 'done')),
  priority TEXT NOT NULL DEFAULT 'medium' CHECK (priority IN ('low', 'medium', 'high')),
  due_date TIMESTAMPTZ,
  checklist JSONB NOT NULL DEFAULT '[]'::jsonb,
  position INTEGER NOT NULL DEFAULT 0 CHECK (position >= 0),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'boards'
      AND column_name = 'id'
      AND data_type = 'uuid'
  ) THEN
    ALTER TABLE tasks DROP CONSTRAINT IF EXISTS tasks_board_id_fkey;

    ALTER TABLE boards RENAME COLUMN id TO legacy_id;
    ALTER TABLE boards ADD COLUMN id BIGINT;

    WITH ordered_boards AS (
      SELECT legacy_id, row_number() OVER (ORDER BY created_at, legacy_id) AS new_id
      FROM boards
    )
    UPDATE boards b
    SET id = ordered_boards.new_id
    FROM ordered_boards
    WHERE b.legacy_id = ordered_boards.legacy_id;

    ALTER TABLE boards DROP CONSTRAINT IF EXISTS boards_pkey;
    ALTER TABLE boards ADD CONSTRAINT boards_pkey PRIMARY KEY (id);

    ALTER TABLE tasks RENAME COLUMN id TO legacy_id;
    ALTER TABLE tasks RENAME COLUMN board_id TO legacy_board_id;
    ALTER TABLE tasks ADD COLUMN id BIGINT;
    ALTER TABLE tasks ADD COLUMN board_id BIGINT;

    WITH ordered_tasks AS (
      SELECT legacy_id, row_number() OVER (ORDER BY created_at, legacy_id) AS new_id
      FROM tasks
    )
    UPDATE tasks t
    SET id = ordered_tasks.new_id
    FROM ordered_tasks
    WHERE t.legacy_id = ordered_tasks.legacy_id;

    UPDATE tasks t
    SET board_id = b.id
    FROM boards b
    WHERE t.legacy_board_id = b.legacy_id;

    ALTER TABLE boards DROP COLUMN legacy_id;
    ALTER TABLE tasks DROP COLUMN legacy_id;
    ALTER TABLE tasks DROP COLUMN legacy_board_id;

    CREATE SEQUENCE IF NOT EXISTS boards_id_seq OWNED BY boards.id;
    PERFORM setval('boards_id_seq', COALESCE((SELECT MAX(id) FROM boards), 1), EXISTS (SELECT 1 FROM boards));
    ALTER TABLE boards ALTER COLUMN id SET DEFAULT nextval('boards_id_seq');

    CREATE SEQUENCE IF NOT EXISTS tasks_id_seq OWNED BY tasks.id;
    PERFORM setval('tasks_id_seq', COALESCE((SELECT MAX(id) FROM tasks), 1), EXISTS (SELECT 1 FROM tasks));
    ALTER TABLE tasks ALTER COLUMN id SET DEFAULT nextval('tasks_id_seq');

    ALTER TABLE tasks
      ADD CONSTRAINT tasks_board_id_fkey
      FOREIGN KEY (board_id) REFERENCES boards(id) ON DELETE CASCADE;
  END IF;
END;
$$;

ALTER TABLE tasks ADD COLUMN IF NOT EXISTS board_id BIGINT;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS checklist JSONB NOT NULL DEFAULT '[]'::jsonb;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'tasks_status_check'
      AND conrelid = 'tasks'::regclass
  ) THEN
    ALTER TABLE tasks DROP CONSTRAINT tasks_status_check;
  END IF;
  ALTER TABLE tasks
    ADD CONSTRAINT tasks_status_check
    CHECK (status IN ('backlog', 'todo', 'in_progress', 'done'));
END;
$$;

CREATE TABLE IF NOT EXISTS profiles (
  user_id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  display_name TEXT,
  avatar_url TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS boards_user_id_idx ON boards (user_id);
CREATE INDEX IF NOT EXISTS boards_user_name_idx ON boards (user_id, name);
CREATE INDEX IF NOT EXISTS tasks_user_id_idx ON tasks (user_id);
CREATE INDEX IF NOT EXISTS tasks_board_status_position_idx ON tasks (board_id, status, position);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'tasks_board_id_fkey'
      AND conrelid = 'tasks'::regclass
  ) THEN
    ALTER TABLE tasks
      ADD CONSTRAINT tasks_board_id_fkey
      FOREIGN KEY (board_id) REFERENCES boards(id) ON DELETE CASCADE;
  END IF;
END;
$$;

INSERT INTO boards (user_id, name)
SELECT DISTINCT t.user_id, 'Main Board'
FROM tasks t
WHERE NOT EXISTS (
  SELECT 1 FROM boards b WHERE b.user_id = t.user_id
);

WITH first_boards AS (
  SELECT DISTINCT ON (user_id) user_id, id
  FROM boards
  ORDER BY user_id, created_at
)
UPDATE tasks t
SET board_id = fb.id
FROM first_boards fb
WHERE t.board_id IS NULL
  AND t.user_id = fb.user_id;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM tasks WHERE board_id IS NULL) THEN
    ALTER TABLE tasks ALTER COLUMN board_id SET NOT NULL;
  END IF;
END;
$$;

ALTER TABLE boards ENABLE ROW LEVEL SECURITY;
ALTER TABLE boards FORCE ROW LEVEL SECURITY;
ALTER TABLE tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE tasks FORCE ROW LEVEL SECURITY;
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE profiles FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "boards_select_own" ON boards;
DROP POLICY IF EXISTS "boards_insert_own" ON boards;
DROP POLICY IF EXISTS "boards_update_own" ON boards;
DROP POLICY IF EXISTS "boards_delete_own" ON boards;

CREATE POLICY "boards_select_own"
ON boards FOR SELECT
TO authenticated
USING (user_id = auth.uid());

CREATE POLICY "boards_insert_own"
ON boards FOR INSERT
TO authenticated
WITH CHECK (user_id = auth.uid());

CREATE POLICY "boards_update_own"
ON boards FOR UPDATE
TO authenticated
USING (user_id = auth.uid())
WITH CHECK (user_id = auth.uid());

CREATE POLICY "boards_delete_own"
ON boards FOR DELETE
TO authenticated
USING (user_id = auth.uid());

DROP POLICY IF EXISTS "tasks_select_own" ON tasks;
DROP POLICY IF EXISTS "tasks_insert_own" ON tasks;
DROP POLICY IF EXISTS "tasks_update_own" ON tasks;
DROP POLICY IF EXISTS "tasks_delete_own" ON tasks;

CREATE POLICY "tasks_select_own"
ON tasks FOR SELECT
TO authenticated
USING (
  user_id = auth.uid()
  AND EXISTS (
    SELECT 1 FROM boards b
    WHERE b.id = tasks.board_id
      AND b.user_id = auth.uid()
  )
);

CREATE POLICY "tasks_insert_own"
ON tasks FOR INSERT
TO authenticated
WITH CHECK (
  user_id = auth.uid()
  AND EXISTS (
    SELECT 1 FROM boards b
    WHERE b.id = tasks.board_id
      AND b.user_id = auth.uid()
  )
);

CREATE POLICY "tasks_update_own"
ON tasks FOR UPDATE
TO authenticated
USING (
  user_id = auth.uid()
  AND EXISTS (
    SELECT 1 FROM boards b
    WHERE b.id = tasks.board_id
      AND b.user_id = auth.uid()
  )
)
WITH CHECK (
  user_id = auth.uid()
  AND EXISTS (
    SELECT 1 FROM boards b
    WHERE b.id = tasks.board_id
      AND b.user_id = auth.uid()
  )
);

CREATE POLICY "tasks_delete_own"
ON tasks FOR DELETE
TO authenticated
USING (
  user_id = auth.uid()
  AND EXISTS (
    SELECT 1 FROM boards b
    WHERE b.id = tasks.board_id
      AND b.user_id = auth.uid()
  )
);

DROP POLICY IF EXISTS "profiles_select_own" ON profiles;
DROP POLICY IF EXISTS "profiles_insert_own" ON profiles;
DROP POLICY IF EXISTS "profiles_update_own" ON profiles;
DROP POLICY IF EXISTS "profiles_delete_own" ON profiles;

CREATE POLICY "profiles_select_own"
ON profiles FOR SELECT
TO authenticated
USING (user_id = auth.uid());

CREATE POLICY "profiles_insert_own"
ON profiles FOR INSERT
TO authenticated
WITH CHECK (user_id = auth.uid());

CREATE POLICY "profiles_update_own"
ON profiles FOR UPDATE
TO authenticated
USING (user_id = auth.uid())
WITH CHECK (user_id = auth.uid());

CREATE POLICY "profiles_delete_own"
ON profiles FOR DELETE
TO authenticated
USING (user_id = auth.uid());

CREATE OR REPLACE FUNCTION boards_set_updated_at_fn()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION tasks_set_updated_at_fn()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION profiles_set_updated_at_fn()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS boards_set_updated_at ON boards;
CREATE TRIGGER boards_set_updated_at
  BEFORE UPDATE ON boards
  FOR EACH ROW
  EXECUTE FUNCTION boards_set_updated_at_fn();

DROP TRIGGER IF EXISTS tasks_set_updated_at ON tasks;
CREATE TRIGGER tasks_set_updated_at
  BEFORE UPDATE ON tasks
  FOR EACH ROW
  EXECUTE FUNCTION tasks_set_updated_at_fn();

INSERT INTO realtime.channels (pattern, description, enabled)
SELECT 'board:%', 'Board updates for Kanban task sync', true
WHERE NOT EXISTS (
  SELECT 1 FROM realtime.channels WHERE pattern = 'board:%'
);

UPDATE realtime.channels
SET description = 'Board updates for Kanban task sync',
    enabled = true
WHERE pattern = 'board:%';

ALTER TABLE realtime.channels ENABLE ROW LEVEL SECURITY;
ALTER TABLE realtime.messages ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "realtime_subscribe_own_boards" ON realtime.channels;
CREATE POLICY "realtime_subscribe_own_boards"
ON realtime.channels FOR SELECT
TO authenticated
USING (
  pattern = 'board:%'
  AND EXISTS (
    SELECT 1 FROM boards b
    WHERE b.id = NULLIF(split_part(realtime.channel_name(), ':', 2), '')::bigint
      AND b.user_id = auth.uid()
  )
);

DROP POLICY IF EXISTS "realtime_read_own_board_messages" ON realtime.messages;
CREATE POLICY "realtime_read_own_board_messages"
ON realtime.messages FOR SELECT
TO authenticated
USING (
  channel_name LIKE 'board:%'
  AND EXISTS (
    SELECT 1 FROM boards b
    WHERE b.id = NULLIF(split_part(channel_name, ':', 2), '')::bigint
      AND b.user_id = auth.uid()
  )
);

CREATE OR REPLACE FUNCTION tasks_notify_realtime_fn()
RETURNS TRIGGER AS $$
DECLARE
  target_board_id BIGINT;
  event_name TEXT;
  payload JSONB;
BEGIN
  IF TG_OP = 'DELETE' THEN
    target_board_id := OLD.board_id;
    event_name := 'task_deleted';
    payload := jsonb_build_object(
      'task_id', OLD.id,
      'board_id', OLD.board_id,
      'status', OLD.status
    );
  ELSIF TG_OP = 'INSERT' THEN
    target_board_id := NEW.board_id;
    event_name := 'task_created';
    payload := jsonb_build_object(
      'task_id', NEW.id,
      'board_id', NEW.board_id,
      'status', NEW.status
    );
  ELSE
    target_board_id := NEW.board_id;
    event_name := CASE
      WHEN OLD.status IS DISTINCT FROM NEW.status THEN 'task_status_changed'
      ELSE 'task_changed'
    END;
    payload := jsonb_build_object(
      'task_id', NEW.id,
      'board_id', NEW.board_id,
      'status', NEW.status,
      'previous_status', OLD.status
    );
  END IF;

  IF target_board_id IS NOT NULL THEN
    PERFORM realtime.publish(
      'board:' || target_board_id::text,
      event_name,
      payload
    );
  END IF;

  RETURN COALESCE(NEW, OLD);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS tasks_notify_realtime ON tasks;
CREATE TRIGGER tasks_notify_realtime
  AFTER INSERT OR UPDATE OR DELETE ON tasks
  FOR EACH ROW
  EXECUTE FUNCTION tasks_notify_realtime_fn();

DROP TRIGGER IF EXISTS profiles_set_updated_at ON profiles;
CREATE TRIGGER profiles_set_updated_at
  BEFORE UPDATE ON profiles
  FOR EACH ROW
  EXECUTE FUNCTION profiles_set_updated_at_fn();

REVOKE ALL ON TABLE boards FROM anon;
REVOKE ALL ON TABLE tasks FROM anon;
REVOKE ALL ON TABLE profiles FROM anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE boards TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE tasks TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE profiles TO authenticated;
GRANT SELECT ON TABLE realtime.channels TO authenticated;
GRANT SELECT ON TABLE realtime.messages TO authenticated;


